#cloud-config
token: token           # replace with a desired token
os:
  ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDSo47RN6s6q/xE6F2NMy+Q0FGko8C/VAZjEhi9bD70v
  password: p@ssword   # replace with a your password
install:
  mode: create
  networks:
    harvester-mgmt:    # The management bond name. This is mandatory.
      interfaces:
      - name: eno1
      default_route: true
      method: dhcp
  device: /dev/sda
  iso_url: https://releases.rancher.com/harvester/v0.3.0/harvester-v0.3.0-amd64.iso
  tty: ttyS1,115200n8
